// Zemax OpticStudio ZMX export (minimal subset)
// - Outputs UTF-16LE (with BOM) for compatibility
// - Supports: STANDARD, EVENASPH (via TYPE EVENASPH + CONI + PARM), COORDBRK
// - Detects unsupported: Aspheric odd

function isBlank(v) {
  return v === null || v === undefined || String(v).trim() === '';
}

function parseNumberOrNull(v) {
  if (v === null || v === undefined) return null;
  if (typeof v === 'number' && Number.isFinite(v)) return v;
  const s = String(v).trim();
  if (s === '') return null;
  if (/^inf(inity)?$/i.test(s)) return Infinity;
  const n = Number(s);
  return Number.isFinite(n) ? n : null;
}

function normalizeMaterialName(material) {
  const s = String(material ?? '').trim();
  if (s === '') return 'AIR';
  // Common variants
  if (s.toUpperCase() === 'AIR') return 'AIR';
  if (s.toUpperCase() === 'VACUUM') return 'AIR';
  // Zemax glass names should not contain whitespace.
  return s.replace(/\s+/g, '');
}

function encodeUtf16LeWithBom(str) {
  // UTF-16LE BOM
  const out = new Uint8Array(2 + str.length * 2);
  out[0] = 0xff;
  out[1] = 0xfe;
  for (let i = 0; i < str.length; i++) {
    const codeUnit = str.charCodeAt(i);
    out[2 + i * 2] = codeUnit & 0xff;
    out[2 + i * 2 + 1] = (codeUnit >> 8) & 0xff;
  }
  return out;
}

function inferUnsupportedSurfaceTypes(rows) {
  const odd = [];

  for (let i = 0; i < rows.length; i++) {
    const r = rows[i] ?? {};
    const surfType = String(r.surfType ?? '').trim();
    if (surfType === 'Aspheric odd') odd.push(i + 1);
  }

  return { odd };
}

function isCoordTransSurface(row) {
  const st = String(row?.surfType ?? row?.['surface type'] ?? row?.surfaceType ?? '').trim().toLowerCase();
  const ot = String(row?.['object type'] ?? row?.object ?? '').trim().toLowerCase();
  return st === 'coord trans' || st === 'coordinate transform' || st === 'ct' || st === 'coordtrans' || st === 'coordinatetransform'
    || ot === 'coord trans' || ot === 'coordinate transform' || ot === 'ct' || ot === 'coordtrans' || ot === 'coordinatetransform';
}

function normalizeCoordReturnToCode(v) {
  const s = String(v ?? '').trim().toLowerCase();
  if (s === 'orientation') return 1;
  if (s === 'xy') return 2;
  if (s === 'xyz') return 3;
  return 0;
}

function formatFloat(v) {
  // Keep Zemax-friendly plain decimals, avoid scientific for typical sizes.
  if (!Number.isFinite(v)) return '0';
  // For very small/large values, scientific is fine.
  const av = Math.abs(v);
  if (av !== 0 && (av < 1e-6 || av > 1e6)) return String(v);
  return Number(v.toFixed(15)).toString();
}

function normalizeArray(value) {
  return Array.isArray(value) ? value : [];
}

function inferPrimaryWavelengthIndexOneBased(sourceRows) {
  for (let i = 0; i < sourceRows.length; i++) {
    const r = sourceRows[i] ?? {};
    const primary = String(r.primary ?? '').trim();
    if (primary) return i + 1;
  }
  return 1;
}

export function generateZMXText(opticalSystemRows, options: any = {}) {
  const rows = Array.isArray(opticalSystemRows) ? opticalSystemRows : [];

  const { odd } = inferUnsupportedSurfaceTypes(rows);
  if (odd.length > 0) {
    const list = odd.slice(0, 20).join(', ');
    const more = odd.length > 20 ? ` (+${odd.length - 20} more)` : '';
    const err: any = new Error(`Zemax export: Aspheric odd surfaces are not supported yet. Surface(s): ${list}${more}`);
    err.code = 'ZMX_UNSUPPORTED_ODD';
    throw err;
  }

  const title = String(options.title ?? 'co-opt export').replace(/\r?\n/g, ' ').trim();
  const units = String(options.units ?? 'MM').trim().toUpperCase();

  const lines = [];
  lines.push(`UNIT ${units}`);
  if (title) lines.push(`NAME "${title.replace(/\"/g, "'")}"`);
  lines.push('NOTE "Generated by co-opt"');

  // --- System-level data (minimal) ---
  // Wavelengths (from source table)
  const sourceRows = normalizeArray(options.sourceRows);
  if (sourceRows.length > 0) {
    // Zemax-style: one WAVM line per wavelength: WAVM <index> <wavelength_um> <weight>
    for (let i = 0; i < sourceRows.length; i++) {
      const r = sourceRows[i] ?? {};
      const wl = parseNumberOrNull(r.wavelength);
      if (wl === null || !Number.isFinite(wl) || wl <= 0) continue;
      const w = parseNumberOrNull(r.weight);
      const weight = (w !== null && Number.isFinite(w)) ? w : 1;
      lines.push(`WAVM ${i + 1} ${formatFloat(wl)} ${formatFloat(weight)}`);
    }

    const primaryIndex = inferPrimaryWavelengthIndexOneBased(sourceRows);
    if (primaryIndex > 0) {
      lines.push(`PWAV ${primaryIndex}`);
    }
  }

  // Fields (from object table)
  const objectRows = normalizeArray(options.objectRows);
  if (objectRows.length > 0) {
    // Co-Opt's object table commonly stores field angles in degrees.
    // Zemax-produced ZMX commonly stores up to 12 fields on one line (lists), e.g.:
    // XFLN x1 x2 ...
    // YFLN y1 y2 ...
    // FWGN w1 w2 ...
    // Use Angle field type.
    lines.push('FTYP 0 0 2 3 0 0 0 2');

    const xs = [];
    const ys = [];
    const ws = [];
    for (let i = 0; i < objectRows.length; i++) {
      const r = objectRows[i] ?? {};
      const x = parseNumberOrNull(r.xHeightAngle);
      const y = parseNumberOrNull(r.yHeightAngle);
      // Skip rows that are entirely blank
      if ((x === null || !Number.isFinite(x)) && (y === null || !Number.isFinite(y))) continue;
      xs.push(formatFloat(Number.isFinite(x) ? x : 0));
      ys.push(formatFloat(Number.isFinite(y) ? y : 0));
      ws.push('1');
    }

    if (xs.length > 0) {
      lines.push(`XFLN ${xs.join(' ')}`);
      lines.push(`YFLN ${ys.join(' ')}`);
      lines.push(`FWGN ${ws.join(' ')}`);
    }
  }

  // Entrance pupil diameter (best-effort; caller can provide via paraxial calc)
  const enpd = parseNumberOrNull(options.entrancePupilDiameterMm ?? options.pupilDiameterMm);
  if (enpd !== null && Number.isFinite(enpd) && enpd > 0) {
    lines.push(`ENPD ${formatFloat(enpd)}`);
  }

  for (let i = 0; i < rows.length; i++) {
    const row = rows[i] ?? {};
    lines.push(`SURF ${i}`);

    if (isCoordTransSurface(row)) {
      lines.push('TYPE COORDBRK');
      lines.push('CURV 0');

      const dz = (() => {
        const explicit = parseNumberOrNull(row.decenterZ);
        if (explicit !== null && Number.isFinite(explicit)) return explicit;
        const legacy = parseNumberOrNull(row.thickness);
        if (legacy !== null && Number.isFinite(legacy)) return legacy;
        return 0;
      })();
      lines.push(`DISZ ${formatFloat(dz)}`);

      const dx = (() => {
        const explicit = parseNumberOrNull(row.decenterX);
        if (explicit !== null && Number.isFinite(explicit)) return explicit;
        const legacy = parseNumberOrNull(row.semidia);
        if (legacy !== null && Number.isFinite(legacy)) return legacy;
        return 0;
      })();
      const dy = (() => {
        const explicit = parseNumberOrNull(row.decenterY);
        if (explicit !== null && Number.isFinite(explicit)) return explicit;
        const legacy = parseNumberOrNull(row.material);
        if (legacy !== null && Number.isFinite(legacy)) return legacy;
        return 0;
      })();
      const tx = (() => {
        const explicit = parseNumberOrNull(row.tiltX);
        if (explicit !== null && Number.isFinite(explicit)) return explicit;
        const legacy = parseNumberOrNull(row.rindex);
        if (legacy !== null && Number.isFinite(legacy)) return legacy;
        return 0;
      })();
      const ty = (() => {
        const explicit = parseNumberOrNull(row.tiltY);
        if (explicit !== null && Number.isFinite(explicit)) return explicit;
        const legacy = parseNumberOrNull(row.abbe);
        if (legacy !== null && Number.isFinite(legacy)) return legacy;
        return 0;
      })();
      const tz = (() => {
        const explicit = parseNumberOrNull(row.tiltZ);
        if (explicit !== null && Number.isFinite(explicit)) return explicit;
        const legacy = parseNumberOrNull(row.conic);
        if (legacy !== null && Number.isFinite(legacy)) return legacy;
        return 0;
      })();
      const ord = (() => {
        const explicit = parseNumberOrNull(row.order);
        const legacy = parseNumberOrNull(row.coef1);
        const raw = (explicit !== null && Number.isFinite(explicit)) ? explicit : ((legacy !== null && Number.isFinite(legacy)) ? legacy : 0);
        return (raw === 1) ? 1 : 0;
      })();

      lines.push(`PARM 1 ${formatFloat(dx)}`);
      lines.push(`PARM 2 ${formatFloat(dy)}`);
      lines.push(`PARM 3 ${formatFloat(tx)}`);
      lines.push(`PARM 4 ${formatFloat(ty)}`);
      lines.push(`PARM 5 ${formatFloat(tz)}`);
      lines.push(`PARM 6 ${formatFloat(ord)}`);

      const returnCode = normalizeCoordReturnToCode(row.coordReturn);
      if (returnCode !== 0) {
        lines.push(`PARM 7 ${formatFloat(returnCode)}`);
        const toSurfRaw = parseNumberOrNull(row.toSurf);
        const toSurf = (toSurfRaw !== null && Number.isFinite(toSurfRaw) && toSurfRaw >= 0) ? Math.trunc(toSurfRaw) : 0;
        lines.push(`PARM 8 ${formatFloat(toSurf)}`);
      }

      const comment = String(row.comment ?? '').trim();
      if (comment) {
        lines.push(`COMM "${comment.replace(/\"/g, "'")}"`);
      }
      continue;
    }

    const objectType = String(row['object type'] ?? '').trim();
    if (objectType === 'Stop') {
      lines.push('STOP');
    }

    // Radius -> curvature
    const radius = parseNumberOrNull(row.radius);
    let curvature = 0;
    if (radius === null) {
      curvature = 0;
    } else if (radius === Infinity) {
      curvature = 0;
    } else if (radius === 0) {
      curvature = 0;
    } else {
      curvature = 1 / radius;
    }
    lines.push(`CURV ${formatFloat(curvature)}`);

    // Thickness
    const thickness = parseNumberOrNull(row.thickness);
    let disz = 0;
    if (thickness === null) {
      disz = 0;
    } else if (thickness === Infinity) {
      // Avoid INF tokens; use large finite placeholder.
      disz = 1e10;
    } else {
      disz = thickness;
    }
    lines.push(`DISZ ${formatFloat(disz)}`);

    // Glass (gap medium after surface)
    const mat = normalizeMaterialName(row.material);
    if (!isBlank(mat) && String(mat).toUpperCase() !== 'AIR') {
      lines.push(`GLAS ${mat}`);
    }

    // Aperture (semi-diameter)
    const semidia = parseNumberOrNull(row.semidia);
    if (semidia !== null && Number.isFinite(semidia) && semidia > 0) {
      // Use circular clear aperture type=1 per common usage.
      lines.push(`DIAM ${formatFloat(semidia)} 1 0 0 1 ""`);
    }

    const surfType = String(row.surfType ?? '').trim();
    if (surfType === 'Aspheric even') {
      lines.push('TYPE EVENASPH');

      const conic = parseNumberOrNull(row.conic);
      if (conic !== null && Number.isFinite(conic) && conic !== 0) {
        lines.push(`CONI ${formatFloat(conic)}`);
      }

      // Map coef1..coef10 => PARM 2..11 (Zemax: PARM 1=unused, PARM 2=A4, PARM 3=A6, ...)
      // co-opt: coef1=A4, coef2=A6, coef3=A8, ... so coefN => PARM (N+1)
      lines.push('PARM 1 0');  // PARM 1 is conventionally 0 (unused) in Zemax
      for (let j = 1; j <= 10; j++) {
        const key = `coef${j}`;
        const val = parseNumberOrNull(row[key]);
        if (val === null || !Number.isFinite(val) || val === 0) continue;
        lines.push(`PARM ${j + 1} ${formatFloat(val)}`);
      }
    } else {
      // Standard / spherical
      const conic = parseNumberOrNull(row.conic);
      if (conic !== null && Number.isFinite(conic) && conic !== 0) {
        // Zemax uses Conic on Standard surfaces too.
        lines.push(`CONI ${formatFloat(conic)}`);
      }
    }

    // Comments
    const comment = String(row.comment ?? '').trim();
    if (comment) {
      lines.push(`COMM "${comment.replace(/\"/g, "'")}"`);
    }
  }

  lines.push('');
  return lines.join('\n');
}

export function downloadZMX(zmxText, filename) {
  const name = String(filename ?? 'co-opt-export.zmx').trim() || 'co-opt-export.zmx';
  const ensured = name.toLowerCase().endsWith('.zmx') ? name : `${name}.zmx`;

  const bytes = encodeUtf16LeWithBom(String(zmxText ?? ''));
  const blob = new Blob([bytes], { type: 'text/plain' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = ensured;
  a.style.display = 'none';
  document.body.appendChild(a);
  a.click();
  window.setTimeout(() => {
    a.remove();
    URL.revokeObjectURL(url);
  }, 0);
}
