use serde::{Deserialize, Serialize};
use serde_json::Value;

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GenerateZmxTextRequest {
    pub optical_system_rows: Vec<Value>,
    #[serde(default)]
    pub source_rows: Vec<Value>,
    #[serde(default)]
    pub object_rows: Vec<Value>,
    pub title: Option<String>,
    pub units: Option<String>,
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct GenerateZmxTextResponse {
    pub zmx_text: String,
}

#[tauri::command]
pub fn generate_zmx_text(req: GenerateZmxTextRequest) -> Result<GenerateZmxTextResponse, String> {
    let title = req
        .title
        .unwrap_or_else(|| "co-opt export".to_string())
        .replace('"', "'")
        .replace(['\r', '\n'], " ");
    let units = req
        .units
        .unwrap_or_else(|| "MM".to_string())
        .trim()
        .to_uppercase();

    let mut lines: Vec<String> = Vec::new();
    lines.push(format!("UNIT {}", if units.is_empty() { "MM" } else { &units }));
    if !title.trim().is_empty() {
        lines.push(format!("NAME \"{}\"", title.trim()));
    }
    lines.push("NOTE \"Generated by co-opt-pro Rust backend\"".to_string());

    for (idx, src) in req.source_rows.iter().enumerate() {
        let wl = get_number(src, &["wavelength"]);
        if !wl.is_finite() || wl <= 0.0 {
            continue;
        }
        let weight = get_number(src, &["weight"]);
        let w = if weight.is_finite() { weight } else { 1.0 };
        lines.push(format!("WAVM {} {} {}", idx + 1, fmt(wl), fmt(w)));
    }
    if !req.source_rows.is_empty() {
        lines.push("PWAV 1".to_string());
    }

    if !req.object_rows.is_empty() {
        lines.push("FTYP 0 0 2 3 0 0 0 2".to_string());
        let mut xs: Vec<String> = Vec::new();
        let mut ys: Vec<String> = Vec::new();
        let mut ws: Vec<String> = Vec::new();
        for obj in &req.object_rows {
            let x = get_number(obj, &["xHeightAngle"]);
            let y = get_number(obj, &["yHeightAngle"]);
            if !x.is_finite() && !y.is_finite() {
                continue;
            }
            xs.push(fmt(if x.is_finite() { x } else { 0.0 }));
            ys.push(fmt(if y.is_finite() { y } else { 0.0 }));
            ws.push("1".to_string());
        }
        if !xs.is_empty() {
            lines.push(format!("XFLN {}", xs.join(" ")));
            lines.push(format!("YFLN {}", ys.join(" ")));
            lines.push(format!("FWGN {}", ws.join(" ")));
        }
    }

    for (i, row) in req.optical_system_rows.iter().enumerate() {
        lines.push(format!("SURF {}", i));

        let object_type = get_string(row, &["object type", "object"]).to_lowercase();
        if object_type == "stop" || object_type == "sto" {
            lines.push("STOP".to_string());
        }

        let radius = get_number(row, &["radius"]);
        let curv = if radius.is_finite() && radius.abs() > f64::EPSILON {
            1.0 / radius
        } else {
            0.0
        };
        lines.push(format!("CURV {}", fmt(curv)));

        let thickness = get_number(row, &["thickness"]);
        let disz = if thickness.is_finite() { thickness } else { 0.0 };
        lines.push(format!("DISZ {}", fmt(disz)));

        let material = normalize_material_name(&get_string(row, &["material"]));
        if !material.is_empty() && material != "AIR" {
            lines.push(format!("GLAS {}", material));
        }

        let semidia = get_number(row, &["semidia", "semiDiameter", "semiDia"]);
        if semidia.is_finite() && semidia > 0.0 {
            lines.push(format!("DIAM {} 1 0 0 1 \"\"", fmt(semidia)));
        }

        let conic = get_number(row, &["conic"]);
        if conic.is_finite() && conic.abs() > f64::EPSILON {
            lines.push(format!("CONI {}", fmt(conic)));
        }
    }

    let mut zmx_text = lines.join("\n");
    zmx_text.push('\n');
    Ok(GenerateZmxTextResponse { zmx_text })
}

fn get_number(value: &Value, keys: &[&str]) -> f64 {
    for key in keys {
        if let Some(v) = value.get(key) {
            if let Some(n) = v.as_f64() {
                return n;
            }
            if let Some(s) = v.as_str() {
                let trimmed = s.trim();
                if trimmed.eq_ignore_ascii_case("inf") || trimmed.eq_ignore_ascii_case("infinity") {
                    return f64::INFINITY;
                }
                if let Ok(n) = trimmed.parse::<f64>() {
                    return n;
                }
            }
        }
    }
    f64::NAN
}

fn get_string(value: &Value, keys: &[&str]) -> String {
    for key in keys {
        if let Some(v) = value.get(key) {
            if let Some(s) = v.as_str() {
                return s.trim().to_string();
            }
            if !v.is_null() {
                return v.to_string().trim_matches('"').trim().to_string();
            }
        }
    }
    String::new()
}

fn normalize_material_name(material: &str) -> String {
    let s = material.trim();
    if s.is_empty() {
        return "AIR".to_string();
    }
    if s.eq_ignore_ascii_case("air") || s.eq_ignore_ascii_case("vacuum") {
        return "AIR".to_string();
    }
    s.split_whitespace().collect::<String>()
}

fn fmt(v: f64) -> String {
    if !v.is_finite() {
        return "0".to_string();
    }
    let abs = v.abs();
    if abs != 0.0 && !(1e-6..=1e6).contains(&abs) {
        return v.to_string();
    }
    format!("{:.15}", v)
        .trim_end_matches('0')
        .trim_end_matches('.')
        .to_string()
}
