use serde::{Deserialize, Serialize};
use serde_json::Value;
use serde_json::{json, Map};

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GenerateZmxTextRequest {
    pub optical_system_rows: Vec<Value>,
    #[serde(default)]
    pub source_rows: Vec<Value>,
    #[serde(default)]
    pub object_rows: Vec<Value>,
    pub title: Option<String>,
    pub units: Option<String>,
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct GenerateZmxTextResponse {
    pub zmx_text: String,
}

#[derive(Debug, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ParseZmxTextRequest {
    pub text: String,
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct ParseZmxTextResponse {
    pub rows: Vec<Value>,
    pub issues: Vec<Issue>,
    pub source_rows: Vec<Value>,
    pub object_rows: Vec<Value>,
    pub entrance_pupil_diameter_mm: Option<f64>,
}

#[derive(Debug, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct Issue {
    pub severity: String,
    pub message: String,
}

#[tauri::command]
pub fn generate_zmx_text(req: GenerateZmxTextRequest) -> Result<GenerateZmxTextResponse, String> {
    let title = req
        .title
        .unwrap_or_else(|| "co-opt export".to_string())
        .replace('"', "'")
        .replace(['\r', '\n'], " ");
    let units = req
        .units
        .unwrap_or_else(|| "MM".to_string())
        .trim()
        .to_uppercase();

    let mut lines: Vec<String> = Vec::new();
    lines.push(format!("UNIT {}", if units.is_empty() { "MM" } else { &units }));
    if !title.trim().is_empty() {
        lines.push(format!("NAME \"{}\"", title.trim()));
    }
    lines.push("NOTE \"Generated by co-opt-pro Rust backend\"".to_string());

    for (idx, src) in req.source_rows.iter().enumerate() {
        let wl = get_number(src, &["wavelength"]);
        if !wl.is_finite() || wl <= 0.0 {
            continue;
        }
        let weight = get_number(src, &["weight"]);
        let w = if weight.is_finite() { weight } else { 1.0 };
        lines.push(format!("WAVM {} {} {}", idx + 1, fmt(wl), fmt(w)));
    }
    if !req.source_rows.is_empty() {
        lines.push("PWAV 1".to_string());
    }

    if !req.object_rows.is_empty() {
        lines.push("FTYP 0 0 2 3 0 0 0 2".to_string());
        let mut xs: Vec<String> = Vec::new();
        let mut ys: Vec<String> = Vec::new();
        let mut ws: Vec<String> = Vec::new();
        for obj in &req.object_rows {
            let x = get_number(obj, &["xHeightAngle"]);
            let y = get_number(obj, &["yHeightAngle"]);
            if !x.is_finite() && !y.is_finite() {
                continue;
            }
            xs.push(fmt(if x.is_finite() { x } else { 0.0 }));
            ys.push(fmt(if y.is_finite() { y } else { 0.0 }));
            ws.push("1".to_string());
        }
        if !xs.is_empty() {
            lines.push(format!("XFLN {}", xs.join(" ")));
            lines.push(format!("YFLN {}", ys.join(" ")));
            lines.push(format!("FWGN {}", ws.join(" ")));
        }
    }

    for (i, row) in req.optical_system_rows.iter().enumerate() {
        lines.push(format!("SURF {}", i));

        let object_type = get_string(row, &["object type", "object"]).to_lowercase();
        if object_type == "stop" || object_type == "sto" {
            lines.push("STOP".to_string());
        }

        let radius = get_number(row, &["radius"]);
        let curv = if radius.is_finite() && radius.abs() > f64::EPSILON {
            1.0 / radius
        } else {
            0.0
        };
        lines.push(format!("CURV {}", fmt(curv)));

        let thickness = get_number(row, &["thickness"]);
        let disz = if thickness.is_finite() { thickness } else { 0.0 };
        lines.push(format!("DISZ {}", fmt(disz)));

        let material = normalize_material_name(&get_string(row, &["material"]));
        if !material.is_empty() && material != "AIR" {
            lines.push(format!("GLAS {}", material));
        }

        let semidia = get_number(row, &["semidia", "semiDiameter", "semiDia"]);
        if semidia.is_finite() && semidia > 0.0 {
            lines.push(format!("DIAM {} 1 0 0 1 \"\"", fmt(semidia)));
        }

        let conic = get_number(row, &["conic"]);
        if conic.is_finite() && conic.abs() > f64::EPSILON {
            lines.push(format!("CONI {}", fmt(conic)));
        }
    }

    let mut zmx_text = lines.join("\n");
    zmx_text.push('\n');
    Ok(GenerateZmxTextResponse { zmx_text })
}

#[tauri::command]
pub fn parse_zmx_text(req: ParseZmxTextRequest) -> Result<ParseZmxTextResponse, String> {
    let lines = req
        .text
        .replace("\r\n", "\n")
        .replace('\r', "\n")
        .lines()
        .map(|s| s.trim().to_string())
        .collect::<Vec<_>>();

    let mut rows: Vec<Value> = Vec::new();
    let mut issues: Vec<Issue> = Vec::new();
    let mut current_surf: Option<usize> = None;

    let mut source_rows: Vec<Value> = Vec::new();
    let mut object_rows: Vec<Value> = Vec::new();
    let mut entrance_pupil_diameter_mm: Option<f64> = None;

    for line in lines {
        if line.is_empty() {
            continue;
        }
        let tokens = tokenize_line(&line);
        if tokens.is_empty() {
            continue;
        }
        let key = tokens[0].to_uppercase();

        if key == "WAVM" {
            let wl = tokens.get(2).and_then(|v| parse_num(v));
            let wt = tokens.get(3).and_then(|v| parse_num(v)).unwrap_or(1.0);
            if let Some(wavelength) = wl {
                source_rows.push(json!({
                    "id": source_rows.len() + 1,
                    "wavelength": wavelength,
                    "weight": wt,
                    "primary": if source_rows.is_empty() { "Primary Wavelength" } else { "" },
                    "angle": 0
                }));
            }
            continue;
        }

        if key == "XFLN" || key == "YFLN" {
            let values = tokens
                .iter()
                .skip(1)
                .filter_map(|t| parse_num(t))
                .collect::<Vec<_>>();
            let count = values.len();
            while object_rows.len() < count {
                object_rows.push(json!({
                    "id": object_rows.len() + 1,
                    "xHeightAngle": 0,
                    "yHeightAngle": 0,
                    "position": "Angle",
                    "angle": 0
                }));
            }
            for (idx, val) in values.iter().enumerate() {
                if let Some(obj) = object_rows.get_mut(idx).and_then(Value::as_object_mut) {
                    if key == "XFLN" {
                        obj.insert("xHeightAngle".to_string(), json!(val));
                    } else {
                        obj.insert("yHeightAngle".to_string(), json!(val));
                    }
                }
            }
            continue;
        }

        if key == "ENPD" {
            entrance_pupil_diameter_mm = tokens.get(1).and_then(|v| parse_num(v));
            continue;
        }

        if key == "SURF" {
            let idx = tokens
                .get(1)
                .and_then(|v| parse_num(v))
                .map(|n| n.max(0.0) as usize);
            if let Some(i) = idx {
                ensure_row(&mut rows, i);
                current_surf = Some(i);
            } else {
                issues.push(Issue {
                    severity: "warning".to_string(),
                    message: format!("Invalid SURF record: {line}"),
                });
            }
            continue;
        }

        if current_surf.is_none() {
            continue;
        }
        let idx = current_surf.unwrap_or(0);
        ensure_row(&mut rows, idx);
        let row = rows[idx].as_object_mut().ok_or("invalid row object")?;

        match key.as_str() {
            "STOP" => {
                row.insert("object type".to_string(), json!("Stop"));
            }
            "CURV" => {
                let curv = tokens.get(1).and_then(|v| parse_num(v)).unwrap_or(0.0);
                let radius = if curv.abs() < f64::EPSILON {
                    Value::String("INF".to_string())
                } else {
                    json!(1.0 / curv)
                };
                row.insert("radius".to_string(), radius);
            }
            "DISZ" => {
                let disz = tokens.get(1).and_then(|v| parse_num(v)).unwrap_or(0.0);
                row.insert("thickness".to_string(), json!(disz));
            }
            "GLAS" => {
                let name = tokens.get(1).cloned().unwrap_or_else(|| "AIR".to_string());
                row.insert("material".to_string(), json!(name));
            }
            "DIAM" => {
                if let Some(v) = tokens.get(1).and_then(|t| parse_num(t)) {
                    row.insert("semidia".to_string(), json!(v));
                }
            }
            "TYPE" => {
                let t = tokens.get(1).cloned().unwrap_or_default().to_uppercase();
                let surf_type = if t == "EVENASPH" {
                    "Aspheric even"
                } else if t == "COORDBRK" {
                    "Coord Trans"
                } else {
                    "Spherical"
                };
                row.insert("surfType".to_string(), json!(surf_type));
            }
            "CONI" => {
                if let Some(v) = tokens.get(1).and_then(|t| parse_num(t)) {
                    row.insert("conic".to_string(), json!(v));
                }
            }
            "PARM" => {
                let j = tokens.get(1).and_then(|t| parse_num(t)).unwrap_or(0.0) as i32;
                let v = tokens.get(2).and_then(|t| parse_num(t)).unwrap_or(0.0);
                if (2..=11).contains(&j) {
                    row.insert(format!("coef{}", j - 1), json!(v));
                }
            }
            "COMM" => {
                let comment = tokens.iter().skip(1).cloned().collect::<Vec<_>>().join(" ");
                row.insert("comment".to_string(), json!(comment.trim_matches('"')));
            }
            _ => {}
        }
    }

    if rows.is_empty() {
        return Err("Zemax import: no SURF records found.".to_string());
    }

    if let Some(first) = rows.first_mut().and_then(Value::as_object_mut) {
        first.insert("object type".to_string(), json!("Object"));
    }
    if let Some(last) = rows.last_mut().and_then(Value::as_object_mut) {
        if !last.contains_key("object type") {
            last.insert("object type".to_string(), json!("Image"));
        }
    }

    for (i, row) in rows.iter_mut().enumerate() {
        if let Some(obj) = row.as_object_mut() {
            obj.insert("id".to_string(), json!(i));
            if !obj.contains_key("surfType") {
                obj.insert("surfType".to_string(), json!("Spherical"));
            }
            for c in 1..=10 {
                obj.entry(format!("coef{c}")).or_insert_with(|| json!(0));
            }
        }
    }

    Ok(ParseZmxTextResponse {
        rows,
        issues,
        source_rows,
        object_rows,
        entrance_pupil_diameter_mm,
    })
}

fn get_number(value: &Value, keys: &[&str]) -> f64 {
    for key in keys {
        if let Some(v) = value.get(key) {
            if let Some(n) = v.as_f64() {
                return n;
            }
            if let Some(s) = v.as_str() {
                let trimmed = s.trim();
                if trimmed.eq_ignore_ascii_case("inf") || trimmed.eq_ignore_ascii_case("infinity") {
                    return f64::INFINITY;
                }
                if let Ok(n) = trimmed.parse::<f64>() {
                    return n;
                }
            }
        }
    }
    f64::NAN
}

fn get_string(value: &Value, keys: &[&str]) -> String {
    for key in keys {
        if let Some(v) = value.get(key) {
            if let Some(s) = v.as_str() {
                return s.trim().to_string();
            }
            if !v.is_null() {
                return v.to_string().trim_matches('"').trim().to_string();
            }
        }
    }
    String::new()
}

fn normalize_material_name(material: &str) -> String {
    let s = material.trim();
    if s.is_empty() {
        return "AIR".to_string();
    }
    if s.eq_ignore_ascii_case("air") || s.eq_ignore_ascii_case("vacuum") {
        return "AIR".to_string();
    }
    s.split_whitespace().collect::<String>()
}

fn fmt(v: f64) -> String {
    if !v.is_finite() {
        return "0".to_string();
    }
    let abs = v.abs();
    if abs != 0.0 && !(1e-6..=1e6).contains(&abs) {
        return v.to_string();
    }
    format!("{:.15}", v)
        .trim_end_matches('0')
        .trim_end_matches('.')
        .to_string()
}

fn tokenize_line(line: &str) -> Vec<String> {
    let mut out = Vec::<String>::new();
    let chars: Vec<char> = line.chars().collect();
    let mut i = 0usize;
    while i < chars.len() {
        while i < chars.len() && chars[i].is_whitespace() {
            i += 1;
        }
        if i >= chars.len() {
            break;
        }
        if chars[i] == '"' {
            i += 1;
            let start = i;
            while i < chars.len() && chars[i] != '"' {
                i += 1;
            }
            out.push(chars[start..i].iter().collect());
            if i < chars.len() && chars[i] == '"' {
                i += 1;
            }
        } else {
            let start = i;
            while i < chars.len() && !chars[i].is_whitespace() {
                i += 1;
            }
            out.push(chars[start..i].iter().collect());
        }
    }
    out
}

fn parse_num(s: &str) -> Option<f64> {
    let t = s.trim();
    if t.is_empty() {
        return None;
    }
    if t.eq_ignore_ascii_case("inf") || t.eq_ignore_ascii_case("infinity") {
        return Some(f64::INFINITY);
    }
    t.parse::<f64>().ok()
}

fn ensure_row(rows: &mut Vec<Value>, idx: usize) {
    while rows.len() <= idx {
        rows.push(make_empty_row(rows.len()));
    }
}

fn make_empty_row(id: usize) -> Value {
    let mut map = Map::<String, Value>::new();
    map.insert("id".to_string(), json!(id));
    map.insert("object type".to_string(), json!(""));
    map.insert("comment".to_string(), json!(""));
    map.insert("surfType".to_string(), json!("Spherical"));
    map.insert("radius".to_string(), json!(""));
    map.insert("thickness".to_string(), json!(""));
    map.insert("semidia".to_string(), json!(""));
    map.insert("material".to_string(), json!(""));
    map.insert("conic".to_string(), json!(0));
    for i in 1..=10 {
        map.insert(format!("coef{i}"), json!(0));
    }
    Value::Object(map)
}
