out fil 'c:/Temp/optalix-meridional-ray-capture.txt'

print 'field wavelength surface x y z cx cy cz'

do $wavelength = 1,3
  do $surface = 1,16
    print 6 $wavelength $surface &
      [X s$surface w$wavelength f6 0 0.75] &
      [Y s$surface w$wavelength f6 0 0.75] &
      [Z s$surface w$wavelength f6 0 0.75] &
      [CX s$surface w$wavelength f6 0 0.75] &
      [CY s$surface w$wavelength f6 0 0.75] &
      [CZ s$surface w$wavelength f6 0 0.75]
  enddo
enddo

out t
