out fil 'c:/Temp/optalix-chief-and-meridional-ray-capture.txt'

print 'field wavelength surface chief_x chief_y chief_z chief_cx chief_cy chief_cz sample_x sample_y sample_z sample_cx sample_cy sample_cz'

do $wavelength = 1,3
  do $surface = 1,16
    print 6 $wavelength $surface &
      [X s$surface w$wavelength f6 0 0] &
      [Y s$surface w$wavelength f6 0 0] &
      [Z s$surface w$wavelength f6 0 0] &
      [CX s$surface w$wavelength f6 0 0] &
      [CY s$surface w$wavelength f6 0 0] &
      [CZ s$surface w$wavelength f6 0 0] &
      [X s$surface w$wavelength f6 0 0.75] &
      [Y s$surface w$wavelength f6 0 0.75] &
      [Z s$surface w$wavelength f6 0 0.75] &
      [CX s$surface w$wavelength f6 0 0.75] &
      [CY s$surface w$wavelength f6 0 0.75] &
      [CZ s$surface w$wavelength f6 0 0.75]
  enddo
enddo

out t