out fil 'c:/Users/yassa/source/co-opt/diagnostics/results/optalix-opd-object-space-capture.txt'

print 'marker field wavelength pupil_y value_1 value_2 value_3'

do $wavelength = 1,3
  do $pupil_y = -1,1,0.25
    print 'opd' 6 $wavelength $pupil_y [OPD f6 w$wavelength 0 $pupil_y]
    print 'surface1_xyz' 6 $wavelength $pupil_y [X s1 w$wavelength f6 0 $pupil_y] [Y s1 w$wavelength f6 0 $pupil_y] [Z s1 w$wavelength f6 0 $pupil_y]
    print 'surface1_dir' 6 $wavelength $pupil_y [CX s1 w$wavelength f6 0 $pupil_y] [CY s1 w$wavelength f6 0 $pupil_y] [CZ s1 w$wavelength f6 0 $pupil_y]
  enddo
enddo

out t